-- Consult America recruitment — initial schema for Neon Postgres.
--
-- This is a clean build. It deliberately shares nothing with the Supabase
-- schema in db/schema/: no Supabase auth.users dependency, no RLS policies
-- referencing auth.uid(), no storage.objects. Authorization is enforced in the
-- application layer against admin_sessions, because Neon has no equivalent of
-- Supabase's request-scoped JWT claims.
--
-- Scope, matching Phase 1: an admin signs in, creates jobs by hand, publishes
-- them, they appear on /careers, a candidate applies, the application lands
-- here and in the recruiting inbox, and a recruiter works it through the CRM
-- stages. Nothing is imported from Zoho or anywhere else.
--
-- Conventions:
--   * ids are uuid, generated by the database
--   * every table carries created_at; mutable tables carry updated_at
--   * enums are CHECK constraints rather than Postgres enum types, because
--     adding a value to a CHECK is a cheap ALTER while adding to an enum type
--     is awkward to reverse
--   * timestamps are timestamptz, always. Storing local time is how you get
--     an off-by-an-hour bug twice a year.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ---------------------------------------------------------------- admin users

-- Consult America staff who can reach the dashboard. There is no public
-- registration: rows are created by another admin or by seed.
CREATE TABLE IF NOT EXISTS admin_users (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email           TEXT NOT NULL,
  -- bcrypt/argon2 output. Never a plaintext or reversible value.
  password_hash   TEXT NOT NULL,
  full_name       TEXT NOT NULL,
  role            TEXT NOT NULL DEFAULT 'RECRUITER'
                    CHECK (role IN ('OWNER', 'ADMIN', 'RECRUITER')),
  is_active       BOOLEAN NOT NULL DEFAULT TRUE,
  -- Set when an admin must choose a new password before doing anything else,
  -- e.g. after a seeded or reset credential.
  must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
  last_login_at   TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Case-insensitive uniqueness: Admin@x.com and admin@x.com are one account.
CREATE UNIQUE INDEX IF NOT EXISTS admin_users_email_key ON admin_users (lower(email));

-- Opaque session tokens, hashed at rest so a database leak cannot be replayed
-- as a login. The raw token lives only in the user's cookie.
CREATE TABLE IF NOT EXISTS admin_sessions (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  admin_user_id   UUID NOT NULL REFERENCES admin_users(id) ON DELETE CASCADE,
  token_hash      TEXT NOT NULL UNIQUE,
  expires_at      TIMESTAMPTZ NOT NULL,
  ip              TEXT,
  user_agent      TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS admin_sessions_user_idx ON admin_sessions (admin_user_id);
CREATE INDEX IF NOT EXISTS admin_sessions_expiry_idx ON admin_sessions (expires_at);

-- Single-use, short-lived tokens for "forgot password". Hashed for the same
-- reason as sessions. used_at is kept rather than deleting the row so a replay
-- attempt is visible.
CREATE TABLE IF NOT EXISTS admin_password_resets (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  admin_user_id   UUID NOT NULL REFERENCES admin_users(id) ON DELETE CASCADE,
  token_hash      TEXT NOT NULL UNIQUE,
  expires_at      TIMESTAMPTZ NOT NULL,
  used_at         TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ----------------------------------------------------------------------- jobs

-- One row per role. There is no separate requisition/posting split here: the
-- Supabase schema had both and it meant every publish touched two tables for
-- no benefit at this scale. status alone decides public visibility.
CREATE TABLE IF NOT EXISTS jobs (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  -- URL segment on /careers. Generated from the title, kept stable across
  -- edits so a shared link does not rot.
  slug                 TEXT NOT NULL UNIQUE,
  reference            TEXT NOT NULL UNIQUE,
  title                TEXT NOT NULL,
  department           TEXT NOT NULL,
  location             TEXT NOT NULL,
  workplace_type       TEXT NOT NULL DEFAULT 'ONSITE'
                         CHECK (workplace_type IN ('REMOTE', 'HYBRID', 'ONSITE')),
  employment_type      TEXT NOT NULL DEFAULT 'FULL_TIME'
                         CHECK (employment_type IN ('FULL_TIME', 'PART_TIME', 'CONTRACT', 'TEMPORARY', 'INTERNSHIP')),
  experience_level     TEXT,
  salary_min           INTEGER,
  salary_max           INTEGER,
  salary_currency      TEXT NOT NULL DEFAULT 'USD',
  -- Free text, rendered as paragraphs. The list fields below are separate so
  -- the careers page can format them without parsing prose.
  description          TEXT NOT NULL,
  responsibilities     TEXT[] NOT NULL DEFAULT '{}',
  requirements         TEXT[] NOT NULL DEFAULT '{}',
  benefits             TEXT[] NOT NULL DEFAULT '{}',
  application_deadline TIMESTAMPTZ,
  -- Only PUBLISHED is visible on /careers. Everything else is internal.
  status               TEXT NOT NULL DEFAULT 'DRAFT'
                         CHECK (status IN ('DRAFT', 'PUBLISHED', 'UNPUBLISHED', 'ARCHIVED')),
  published_at         TIMESTAMPTZ,
  created_by           UUID REFERENCES admin_users(id) ON DELETE SET NULL,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- A salary range that reads backwards is a data-entry slip, not a valid state.
  CONSTRAINT jobs_salary_range_ck CHECK (
    salary_min IS NULL OR salary_max IS NULL OR salary_min <= salary_max
  )
);

-- The careers page lists published roles newest first; this is its index.
CREATE INDEX IF NOT EXISTS jobs_public_idx ON jobs (published_at DESC) WHERE status = 'PUBLISHED';
CREATE INDEX IF NOT EXISTS jobs_status_idx ON jobs (status);

-- ----------------------------------------------------------------- candidates

-- A person, deduplicated on email. One candidate can hold many applications.
CREATE TABLE IF NOT EXISTS candidates (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email           TEXT NOT NULL,
  first_name      TEXT NOT NULL,
  last_name       TEXT NOT NULL,
  phone           TEXT,
  location        TEXT,
  linkedin_url    TEXT,
  portfolio_url   TEXT,
  -- Zoho CRM contact id, written by the sync job. Nullable because an
  -- application must never be blocked by CRM availability.
  zoho_contact_id TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS candidates_email_key ON candidates (lower(email));
CREATE INDEX IF NOT EXISTS candidates_zoho_idx ON candidates (zoho_contact_id) WHERE zoho_contact_id IS NOT NULL;

-- --------------------------------------------------------------- applications

CREATE TABLE IF NOT EXISTS applications (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Quoted to the candidate in their confirmation email.
  reference            TEXT NOT NULL UNIQUE,
  job_id               UUID NOT NULL REFERENCES jobs(id) ON DELETE RESTRICT,
  candidate_id         UUID NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
  -- The CRM pipeline. Terminal states are HIRED, REJECTED and WITHDRAWN.
  status               TEXT NOT NULL DEFAULT 'NEW'
                         CHECK (status IN ('NEW', 'SCREENING', 'INTERVIEW', 'SHORTLISTED', 'OFFER', 'HIRED', 'REJECTED', 'WITHDRAWN')),
  -- Vercel Blob URL. The blob itself is private; the app issues access.
  resume_url           TEXT,
  resume_filename      TEXT,
  resume_size_bytes    INTEGER,
  relevant_experience  TEXT,
  additional_info      TEXT,
  source               TEXT NOT NULL DEFAULT 'careers',
  assigned_recruiter_id UUID REFERENCES admin_users(id) ON DELETE SET NULL,
  zoho_synced_at       TIMESTAMPTZ,
  applied_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- jobs uses ON DELETE RESTRICT above on purpose: deleting a job that has
-- applications would orphan real people's submissions. Archive it instead.

-- One application per person per role. A second submission updates the first
-- rather than creating a duplicate the recruiter has to reconcile.
CREATE UNIQUE INDEX IF NOT EXISTS applications_job_candidate_key ON applications (job_id, candidate_id);
CREATE INDEX IF NOT EXISTS applications_status_idx ON applications (status);
CREATE INDEX IF NOT EXISTS applications_job_idx ON applications (job_id);
CREATE INDEX IF NOT EXISTS applications_recent_idx ON applications (applied_at DESC);

-- ------------------------------------------------------------------- CRM bits

CREATE TABLE IF NOT EXISTS application_notes (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  application_id  UUID NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
  author_id       UUID REFERENCES admin_users(id) ON DELETE SET NULL,
  body            TEXT NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS application_notes_app_idx ON application_notes (application_id, created_at DESC);

-- Append-only audit of what happened to an application and who did it.
-- Never updated or deleted: the history is the point.
CREATE TABLE IF NOT EXISTS application_activities (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  application_id  UUID NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
  actor_id        UUID REFERENCES admin_users(id) ON DELETE SET NULL,
  kind            TEXT NOT NULL
                    CHECK (kind IN ('APPLIED', 'STATUS_CHANGED', 'NOTE_ADDED', 'RECRUITER_ASSIGNED', 'EMAIL_SENT', 'INTERVIEW_SCHEDULED', 'INTERVIEW_COMPLETED', 'CRM_SYNCED')),
  from_status     TEXT,
  to_status       TEXT,
  detail          TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS application_activities_app_idx ON application_activities (application_id, created_at DESC);

-- ------------------------------------------------------------------ interviews

-- Shaped so a ConsultHire AI interview result can be attached later without a
-- migration. Deliberately not required by Easy Apply in Phase 1.
CREATE TABLE IF NOT EXISTS interviews (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  application_id          UUID NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
  kind                    TEXT NOT NULL DEFAULT 'AI_SCREEN'
                            CHECK (kind IN ('AI_SCREEN', 'PHONE', 'TECHNICAL', 'PANEL', 'FINAL')),
  status                  TEXT NOT NULL DEFAULT 'SCHEDULED'
                            CHECK (status IN ('SCHEDULED', 'COMPLETED', 'CANCELLED', 'NO_SHOW')),
  scheduled_at            TIMESTAMPTZ,
  completed_at            TIMESTAMPTZ,
  -- Identifier in ConsultHire, so a result can be pulled back and linked.
  consulthire_interview_id TEXT,
  score                   NUMERIC(5, 2),
  summary                 TEXT,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS interviews_app_idx ON interviews (application_id);

-- -------------------------------------------------------------- Zoho CRM sync

-- A durable outbox. An application is saved first and enqueued here second, so
-- CRM downtime can never lose a submission — the worst case is a row sitting
-- at PENDING until the next retry.
CREATE TABLE IF NOT EXISTS zoho_sync_queue (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  entity_type     TEXT NOT NULL CHECK (entity_type IN ('CANDIDATE', 'APPLICATION')),
  entity_id       UUID NOT NULL,
  operation       TEXT NOT NULL CHECK (operation IN ('UPSERT', 'UPDATE_STATUS')),
  status          TEXT NOT NULL DEFAULT 'PENDING'
                    CHECK (status IN ('PENDING', 'IN_PROGRESS', 'SUCCEEDED', 'FAILED', 'ABANDONED')),
  attempts        INTEGER NOT NULL DEFAULT 0,
  last_error      TEXT,
  -- Exponential backoff target. The worker claims rows where this has passed.
  next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  zoho_record_id  TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS zoho_sync_due_idx ON zoho_sync_queue (next_attempt_at)
  WHERE status IN ('PENDING', 'FAILED');
CREATE INDEX IF NOT EXISTS zoho_sync_entity_idx ON zoho_sync_queue (entity_type, entity_id);

-- OAuth tokens for the Zoho CRM connection. Single row expected, but keyed by
-- a name so a sandbox and a production connection can coexist during testing.
CREATE TABLE IF NOT EXISTS zoho_oauth_tokens (
  name            TEXT PRIMARY KEY,
  refresh_token   TEXT NOT NULL,
  access_token    TEXT,
  access_expires_at TIMESTAMPTZ,
  api_domain      TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ------------------------------------------------------------- updated_at glue

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'admin_users', 'jobs', 'candidates', 'applications', 'interviews',
    'zoho_sync_queue', 'zoho_oauth_tokens'
  ] LOOP
    EXECUTE format(
      'DROP TRIGGER IF EXISTS %I ON %I; CREATE TRIGGER %I BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION set_updated_at();',
      t || '_set_updated_at', t, t || '_set_updated_at', t
    );
  END LOOP;
END $$;
